### PR TITLE
V1.4 Exam

### LINKED ISSUE #177: Split up LogicTest

### LINKED ISSUE #194: Able to add duplicate entry multiple times
**Describe the bug**
User is able to add in grades multiple times. 

**To Reproduce**
addgrades 1 1 89
addgrades 1 1 -1

**Expected behavior**
Should throw an error when attempting to add data that is already there. 

<hr>

**Reported by:** @icedcoffeeboy
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#385]</sub>

### PR DESCRIPTION
**Pull request by micklwl**
Update methods and documentation.
Update format of printing exam.
Updated AttendanceTest so it does not erase the developer's storage files.
Resolved #177, #197, #200

### CODE REVIEW

File: src/seedu/addressbook/formatter/Formatter.java [hunk 1]
```diff
@@ -147,4 +147,24 @@ public static String formatAssessments(List<? extends Assessment> assessments) {
...
+     */
+    public static String getPrintableExam(String examName, String subjectName, String examDate, String examStartTime,
+                                          String examEndTime, String examDetails, int takers, boolean isPrivate) {
+        final String examFormat = "%1$sExam: %2$s %3$s %4$s %5$s %6$s %7$s. %9$s: %8$d";
+        String takerWord;
+        if (takers == 1) {
+            takerWord = "Taker";
+        } else {
+            takerWord = "Takers";
+        }
```
Comment (0WN463) [inline src/seedu/addressbook/formatter/Formatter.java]: Very small nitpick, takerWord can be final

Comment (micklwl) [reply src/seedu/addressbook/formatter/Formatter.java]: Resolved.

**Comment by micklwl** [comment]
Resolved #177
